{
	"File": {
		"__typename": "FileMatch",
		"repository": {
			"name": "github.com/Apicurio/apicurio-data-models"
		},
		"file": {
			"name": "rename-response-definition.before.json",
			"path": "src/test/resources/fixtures/cmd/commands/rename-response-definition/openapi-3/rename-response-definition.before.json",
			"content": "{\n    \"openapi\": \"3.0.2\",\n    \"info\": {\n        \"title\": \"Rename Response Definition Test\",\n        \"version\": \"1.0.0\"\n    },\n    \"paths\": {\n        \"/test\": {\n            \"get\": {\n                \"responses\": {\n                    \"200\": {},\n                    \"500\": {\n                        \"$ref\": \"#/components/responses/Error\"\n                    }\n                }\n            },\n            \"post\": {\n                \"responses\": {\n                    \"201\": {},\n                    \"500\": {\n                        \"$ref\": \"#/components/responses/Error\"\n                    }\n                }\n            }\n        }\n    },\n    \"components\": {\n        \"responses\": {\n            \"Error\": {\n                \"content\": {\n                    \"application/json\": {\n                        \"schema\": {\n                            \"type\": \"array\",\n                            \"items\": {\n                                \"type\": \"string\"\n                            }\n                        }\n                    }\n                },\n                \"description\": \"The error response.\"\n            }\n        }\n    }\n}"
		}
	},
	"Error": "panic: runtime error: index out of range [0] with length 0"
}