{
	"File": {
		"__typename": "FileMatch",
		"repository": {
			"name": "github.com/ContextMapper/context-map-discovery"
		},
		"file": {
			"name": "oas-with-error.yml",
			"size": 0,
			"path": "src/test/resources/test/oas-tests/oas-with-error.yml",
			"byteSize": 366,
			"content": "openapi: 3.0.1\ninfo:\n  title: ReferenceManagementServiceAPI\n  version: \"1.0\"\npaths:\n  /ErrorTest:\n    get:\n      operationId: operation1\n      responses:\n        \"200\":\n          description: response message payload (success case)\n    get:\n      operationId: operation1\n      responses:\n        \"200\":\n          description: response message payload (success case)\n",
			"canonicalURL": "/github.com/ContextMapper/context-map-discovery@d5ef0573ccad7502471c90243ea64f6b0bebd168/-/blob/src/test/resources/test/oas-tests/oas-with-error.yml",
			"externalURLs": [
				{
					"url": "https://github.com/ContextMapper/context-map-discovery/blob/d5ef0573ccad7502471c90243ea64f6b0bebd168/src/test/resources/test/oas-tests/oas-with-error.yml",
					"serviceKind": "GITHUB"
				}
			]
		}
	},
	"Error": "unmarshal: yaml: unmarshal errors:\n  yaml: line 12: mapping key \"get\" already defined at line 7"
}